services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_DB: pump_swap_data
      CLICKHOUSE_USER: "bonk"
      CLICKHOUSE_PASSWORD: ""  # Empty password
      CLICKHOUSE_LOG_LEVEL: "debug"  # "trace", "debug", "information", "warning", "error"
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
#      - ./clickhouse-config:/etc/clickhouse-server/config.d  # Optional custom config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 10s
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data: