version: '3.8'

services:

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: pump_swap_data
      CLICKHOUSE_USER: "bonk"
      CLICKHOUSE_PASSWORD: ""  # Empty password
      CLICKHOUSE_LOG_LEVEL: "debug"  # "trace", "debug", "information", "warning", "error"
    # Add health check
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

#  pump-ingestor:
#    build: .
#    depends_on:
#      clickhouse:
#        condition: service_healthy
#    environment:
#      - CLICKHOUSE_URL=http://clickhouse:8123
#      - RUST_BACKTRACE=1
#    restart: unless-stopped

volumes:
  clickhouse_data: